### PR TITLE
twilight

### PR DESCRIPTION
**Pull request by DAPYXY**
added twilight calculations

### CODE REVIEW

**Comment by mklein994** [comment]
Hey @DAPYXY, thanks for the PR! This is so cool -- I've secretly been wanting this feature, I just didn't know how to implement it. I don't know _anything_ about astronomy math; I just forked this repo because I didn't want the extra `approx` dependency (since its only used for tests), and to experiment with updating it to the Rust 2018 syntax.

I love that you implemented this feature though! Would you mind explaining what you did to make this work? I'd love to learn. As I mentioned, I'm not familiar with the formulas and so on, so it would be neat if you'd be willing to share how it works, and where some of these numbers come from (like `Azimuth::Official => 5.0 / 6.0` and so on).

You might want to reach out to @nathan-osman (if he's still maintaining that [repo](https://github.com/nathan-osman/rust-sunrise)), if you're looking for some proper feedback. It looks like he's made some recent commits to https://github.com/nathan-osman/go-sunrise, and I'd expect the math to be the same.

**Comment by DAPYXY** [comment]
@mklein994  Hi Matthew! Yeah no worries I wasn't sure which fork to make the pull request to, since I used your commits I thought I'd send it through you. I can close this request and send it on to Nathan if that makes more sense. Just let me know.

As for the math, it's fairly basic. A sunset/sunrise is defined as when the sun completely disappears below the horizon as observed in a particular place. In a perfect world, if measured from the centre of the sun, that would be when the disc is at a 90° angle from the observer plus a little bit to account for the semi-diameter of the sun. In reality the light is also subject to refraction, so for the sun to completely disappear below the horizon it needs to even further below this 90° + semi-diameter angle. Most generalized equations (like the one we are using) use an accepted value of 50 arc-minutes beyond 90° to account for both. This is where Azimuth::Official => 5.0 / 6.0 comes from. It should be 90° 50', but the equation only needs the deviation from the horizon. 50'/60' = 0.8333°. 

https://en.wikipedia.org/wiki/Sunrise_equation#Generalized_equation

As for twilight, it's the same principal except a different deviation from the horizon. Civil twilight is defined as when the centre of the sun's disc is 6° below the horizon, Nautical = 12° and astronomical = 18°. You don't need to account for the semi-diameter or refraction in these cases.

https://en.wikipedia.org/wiki/Sunset#/media/File:Twilight_subcategories.svg

To implement this in the library I just needed to make the azimuth value a variable. I moved the original code to a new function (time_of_transit) that allowed for this, and then wrapped that function with the sunrise_sunset, civil_twilight etc functions that pass the respective azimuth values to the equation. This preserves the functionality of the original code, while enhancing it with the option to calculate twilight.

Hope that helps

**Comment by mklein994** [comment]
Cool. I'd see if you can contact Nathan, and If he doesn't respond in a couple of days, we can merge this in. We can keep this PR open in the meantime, if you want.

Thanks for the explanation, that really simplifies it for me. Does this also explain why some of the numbers in the tests have changed? I don't have an issue with that, I'm just curious. For example:

https://github.com/mklein994/rust-sunrise/pull/1/files#diff-e141104702f71b7c442d9de4845864886667934796e547fc30720eb740a90147L58-R105

**Comment by DAPYXY** [comment]
Yes that just comes down to the refraction value he's using. Nathan has chose to use -0.01449, which works out to 0.8024° vs the 0.8333° I mention above. It doesn't really matter what you pick as local environmental factors will introduce additional refraction errors. I just chose to go with the value that is cited on the wikipedia article from which his program was based. This equation is very general by design and has quite a few limitations. If you're interested there's quite a good paper on the efficacy of various methods of calculating sunrise times. 

https://digitalcommons.mtu.edu/etdr/697/

I'll just close this pull request and send him one to keep things simple. Cheers!

**Pull request closed without merging**
